### ISSUE TITLE
how to create config for 3 devices

### ISSUE THREAD

**Issue by pdrobek** [Antoxa1081/smart-ess-api-gateway#2]
Hi

I am using your proxy and found it useful in case one device. Many thanks for that. But tell me what should i change in .env for 3 of devices.

**Comment by Antoxa1081** [comment]
Thank you for your interest in my project! 

Now I have released a new update that will allow dynamically passing the target device's identity to get information.
You can specify for each device identity by passings query parameters on `GET /data request` instead base .env parameters.

pn
sn
devcode
devaddr

`GET /data?pn=Q0000000000001&sn=55555555555551&devcode=2428&devaddr=5`
`GET /data?pn=Q0000000000002&sn=55555555555552&devcode=2428&devaddr=5`
`GET /data?pn=Q0000000000003&sn=55555555555553&devcode=2428&devaddr=5`

for HA templates changed as

```yaml
rest:
  # first device
  - resource: "http://localhost:3000/data?pn=Q0000000000001&sn=55555555555551&devcode=2428&devaddr=5"
    sensor:
      - name: "solar_inverter_1_pv_output_power"
        unique_id: "solar_inverter_1_pv_output_power"
        value_template: "{{ value_json.formattedData.solar_pv_power }}"
        device_class: power
        unit_of_measurement: "W"
  # second device
  - resource: "http://localhost:3000/data?pn=Q0000000000002&sn=55555555555552&devcode=2428&devaddr=5"
    sensor:
      - name: "solar_inverter_2_pv_output_power"
        unique_id: "solar_inverter_2_pv_output_power"
        value_template: "{{ value_json.formattedData.solar_pv_power }}"
        device_class: power
        unit_of_measurement: "W"
```

**Comment by pdrobek** [comment]
thank you, do you have any plans to create whole service to get/parse data directly from devices, not from dessmonitor?

**Comment by Antoxa1081** [comment]
I have a project in the process of developing to receive data via RS485, but at the moment there are some difficulties with tracking the data via the protocol (each inverter has its own data addresses) and this solution require psyhical connection to inverter via RS485-USB cable from micro-pc or else. I also have an implementation option with receiving data from a WiFi-Plug pro dongle in local network, using plug own tcp protocol, but experencied unstable connect issues.

**Comment by pdrobek** [comment]
i would glad to see your local network stuff, i have 3 of wifi plug pro devices. 

`rest:
  - resource: "http://localurl:3000/data"
    sensor:
      - name: "solar_inverter_pv_output_power"
        unique_id: "solar_inverter_pv_output_power"
        value_template: "{{ value_json.formattedData.solar_pv_power }}"
        device_class: power
        unit_of_measurement: "W"`

should it create in HA device called "solar_inverter_pv_output_power" im asking because in my case it don't

**Comment by Antoxa1081** [comment]
It should create sensor entity (not device) 

![Image](https://github.com/user-attachments/assets/3c40689e-9e25-409e-ad00-d9e5b970f6c4)

https://www.home-assistant.io/integrations/sensor.rest/

**Comment by pdrobek** [comment]
i haven't any entity, please look at my json file and help me with entity names. How often it will update values?

{
  "webQueryDeviceEnergyFlowEs": {
    "brand": 0,
    "status": 0,
    "date": "2025-02-01 01:00:38",
    "bt_status": [
      {
        "par": "bt_battery_capacity",
        "val": "100.0000",
        "unit": "%",
        "status": -1
      },
      {
        "par": "battery_active_power",
        "val": "0",
        "status": 0
      }
    ],
    "pv_status": [
      {
        "par": "pv_output_power",
        "val": "0.0030",
        "unit": "kW",
        "status": 0
      }
    ],
    "gd_status": [
      {
        "par": "grid_active_power",
        "val": "0",
        "status": 1
      }
    ],
    "bc_status": [
      {
        "par": "load_active_power",
        "val": "0.3860",
        "unit": "kW",
        "status": -1
      }
    ],
    "ol_status": [
      {
        "par": "oil_output_power",
        "val": "0",
        "status": 0
      }
    ],
    "we_status": [
      {
        "par": "wind_output_power",
        "val": "0",
        "status": 0
      }
    ],
    "mi_status": [],
    "mt_status": [],
    "wp_status": []
  },
  "querySPDeviceLastData": {
    "gts": "2025-01-31 17:58:33",
    "pars": {
      "gd_": [
        {
          "id": "gd_ac_input_frequency",
          "par": "AC Input Frequency",
          "val": "49.9",
          "unit": "Hz"
        },
        {
          "id": "gd_mains_status",
          "par": "Mains Status",
          "val": "Mains Discharge"
        },
        {
          "id": "gd_ac_input_voltage",
          "par": "AC Input Voltage",
          "val": "242.1",
          "unit": "V"
        },
        {
          "id": "gd_ac_input_range",
          "par": "AC Input Range",
          "val": "Appliance"
        }
      ],
      "sy_": [
        {
          "id": "sy_status",
          "par": "Working State",
          "val": "Line Mode"
        },
        {
          "id": "sy_nonimal_output_apparent_power",
          "par": "Nonimal Output Apparent Power",
          "val": "4200",
          "unit": "VA"
        },
        {
          "id": "sy_nominal_output_voltage",
          "par": "Nominal Output Voltage",
          "val": "230",
          "unit": "V"
        },
        {
          "id": "sy_nominal_output_frequency",
          "par": "Nominal Output Frequency",
          "val": "50.0",
          "unit": "Hz"
        },
        {
          "id": "sy_main_cpu_version",
          "par": "Main CPU Version",
          "val": "7501"
        },
        {
          "id": "sy_nonimal_output_active_power",
          "par": "Nonimal Output Active Power",
          "val": "4200",
          "unit": "W"
        },
        {
          "id": "sy_nominal_output_current",
          "par": "Nominal Output Current",
          "val": "18",
          "unit": "A"
        },
        {
          "id": "sy_rated_battery_voltage",
          "par": "Rated Battery Voltage",
          "val": "24.0",
          "unit": "V"
        },
        {
          "id": "sy_nominal_ac_current",
          "par": "Nominal AC Current",
          "val": "18",
          "unit": "A"
        },
        {
          "id": "sy_secondary_cpu_version",
          "par": "Secondary CPU Version",
          "val": "0"
        },
        {
          "id": "sy_nominal_ac_voltage",
          "par": "Nominal AC Voltage",
          "val": "230",
          "unit": "V"
        },
        {
          "id": "sy_battery_piece",
          "par": "Battery Piece",
          "val": "24V(3KW)"
        },
        {
          "id": "sy_machine_type",
          "par": "Machine Type",
          "val": "N/A"
        }
      ],
      "pv_": [
        {
          "id": "pv_power",
          "par": "PV1 Input Power",
          "val": "3",
          "unit": "W"
        },
        {
          "id": "pv_status",
          "par": "PV Status",
          "val": "PV Undervoltage"
        },
        {
          "id": "pv_output_power",
          "par": "PV total Power",
          "val": "3",
          "unit": "W"
        },
        {
          "id": "pv_input_voltage",
          "par": "PV1 Input Voltage",
          "val": "0.0",
          "unit": "V"
        }
      ],
      "bt_": [
        {
          "id": "bt_utility_charge",
          "par": "Max Utility Charge Current",
          "val": "30",
          "unit": "A"
        },
        {
          "id": "bt_battery_equalization_voltage",
          "par": "Battery Equalization Voltage",
          "val": "29.2",
          "unit": "V"
        },
        {
          "id": "bt_battery_charging_current",
          "par": "Battery Charging Current",
          "val": "0",
          "unit": "A"
        },
        {
          "id": "bt_vulk_charging_voltage",
          "par": "Bulk Charging Voltage",
          "val": "28.2",
          "unit": "V"
        },
        {
          "id": "bt_battery_equalization_interval",
          "par": "Battery Equalization Interval",
          "val": "30",
          "unit": "day"
        },
        {
          "id": "bt_battery_type",
          "par": "Battery Type",
          "val": "AGM"
        },
        {
          "id": "bt_battery_status",
          "par": "Battery Status",
          "val": "Charging Batteries"
        },
        {
          "id": "bt_battery_equalized_time",
          "par": "Battery Equalized Time",
          "val": "60",
          "unit": "min"
        },
        {
          "id": "bt_comeback_utility_iode",
          "par": "Comeback Utility Mode Voltage Point Under (SBU Priority)",
          "val": "23.0",
          "unit": "V"
        },
        {
          "id": "bt_battery_capacity",
          "par": "Battery Capacity",
          "val": "100",
          "unit": "%"
        },
        {
          "id": "bt_battery_discharge_current",
          "par": "Battery Discharge Current",
          "val": "0",
          "unit": "A"
        },
        {
          "id": "bt_floating_charging_voltage",
          "par": "Floating Charging Voltage",
          "val": "27.0",
          "unit": "V"
        },
        {
          "id": "bt_battery_voltage",
          "par": "Battery Voltage",
          "val": "27.0",
          "unit": "V"
        },
        {
          "id": "bt_battery_mode_voltage",
          "par": "Comeback Battery Mode Voltage Point Under (SBU Priority)",
          "val": "27.0",
          "unit": "V"
        },
        {
          "id": "bt_battery_equalized_timeout",
          "par": "Battery Equalized Timeout",
          "val": "120",
          "unit": "min"
        },
        {
          "id": "bt_battery_cut_off_voltage",
          "par": "Low Battery Cut-off Voltage",
          "val": "20.0",
          "unit": "V"
        },
        {
          "id": "bt_total_charge_current",
          "par": "Max Total Charge Current",
          "val": "60",
          "unit": "A"
        },
        {
          "id": "bt_charger_source_priority",
          "par": "Charger Source Priority",
          "val": "Solar and mains"
        }
      ],
      "bc_": [
        {
          "id": "bc_output_apparent_power",
          "par": "Output Apparent Power",
          "val": "508",
          "unit": "VA"
        },
        {
          "id": "bc_output_voltage",
          "par": "Output Voltage",
          "val": "242.1",
          "unit": "V"
        },
        {
          "id": "bc_load_status",
          "par": "Load Status",
          "val": "Load On (Normal)"
        },
        {
          "id": "bc_output_frequency",
          "par": "Output Frequency",
          "val": "49.9",
          "unit": "Hz"
        },
        {
          "id": "bc_output_source_priority",
          "par": "Output Source Priority",
          "val": "Solar"
        },
        {
          "id": "bc_battery_capacity",
          "par": "AC Output Load",
          "val": "12",
          "unit": "%"
        }
      ]
    }
  },
  "queryDeviceParsEs": {
    "parameter": [
      {
        "par": "bc_output_voltage",
        "name": "Output Voltage",
        "val": "242.1000",
        "unit": "V"
      },
      {
        "par": "bt_battery_capacity",
        "name": "Battery Capacity",
        "val": "100.0000",
        "unit": "%"
      },
      {
        "par": "bt_battery_discharge_current",
        "name": "Battery Discharge Current",
        "val": "0.0000",
        "unit": "A"
      },
      {
        "par": "gd_ac_input_voltage",
        "name": "AC Input Voltage",
        "val": "242.1000",
        "unit": "V"
      },
      {
        "par": "pv_input_voltage",
        "name": "PV1 Input Voltage",
        "val": "0.0000",
        "unit": "V"
      }
    ]
  },
  "formattedData": {
    "battery_voltage": "27.0",
    "battery_status": "Charging Batteries",
    "battery_charging_current": "0",
    "battery_discharge_current": "0",
    "battery_charger_source_priority": "Solar and mains",
    "solar_pv_voltage": "0.0",
    "solar_grid_in_voltage": "242.1",
    "solar_pv_power": "3",
    "output_source_priority": "Solar",
    "battery_real_level": "95.0"
  }
}

**Comment by Antoxa1081** [comment]
have you updated your configuration.yaml in HA and restarted HA server? (example in readme.md attached)
```yaml
rest:
  - resource: "http://localhost:3000/data"
    sensor:
      - name: "solar_inverter_pv_output_power"
        unique_id: "solar_inverter_pv_output_power"
        value_template: "{{ value_json.formattedData.solar_pv_power }}"
        device_class: power
        unit_of_measurement: "W"

      - name: "solar_inverter_load_active_power"
        value_template: "{{ value_json.webQueryDeviceEnergyFlowEs.bc_status|selectattr('par', 'equalto', 'load_active_power')|map(attribute='val')|first|float }}"
        device_class: power
        unit_of_measurement: "kW"

      - name: "solar_inverter_gd_grid_voltage"
        value_template: "{{ value_json.formattedData.solar_grid_in_voltage }}"
        device_class: voltage
        unit_of_measurement: "V"

      - name: "solar_inverter_pv_voltage"
        value_template: "{{ value_json.formattedData.solar_pv_voltage }}"
        device_class: voltage
        unit_of_measurement: "V"

      - name: "solar_inverter_pv_input_current"
        value_template: "{{ 0 }}"
        device_class: current
        unit_of_measurement: "A"

      - name: "solar_inverter_bt_discharge_current"
        value_template: "{{ value_json.formattedData.battery_discharge_current }}"
        device_class: current
        unit_of_measurement: "A"

      - name: "solar_inverter_bt_battery_voltage"
        value_template: "{{ value_json.formattedData.battery_voltage }}"
        device_class: voltage
        unit_of_measurement: "V"


      - name: "solar_inverter_bt_real_level"
        value_template: "{{ value_json.formattedData.battery_real_level }}"
        device_class: battery
        unit_of_measurement: "%"


      - name: "solar_inverter_bt_charging_current"
        value_template: "{{ value_json.formattedData.battery_charging_current }}"
        device_class: current
        unit_of_measurement: "A"

      - name: "solar_inverter_priority"
        value_template: "{{ value_json.formattedData.output_source_priority }}"
        device_class: enum

      - name: "solar_inverter_battery_status"
        value_template: "{{ value_json.formattedData.battery_status }}"
        device_class: enum

      - name: "solar_inverter_battery_charger_source_priority"
        value_template: "{{ value_json.formattedData.battery_charger_source_priority }}"
        device_class: enum
```
